// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'signout': 'Sign Out',
  'signin':'Sign In',
  'signup': 'Sign Up',
  'myrequest_tabname': 'My Requests',
  'favorites_tabname': 'Favoorites',
  'unacceptedrequests_tabname': 'Unaccepted',
  'acceptedrequests_tabname': 'Accepted',
  'donerequests_tabname': 'Completed',
  'name': 'Name',
  'telephone': 'Telephone',
  'password': 'Password',
  'service': 'Service',
  'username': 'Username',
  'address': 'Address',
  'feedbacks': 'Feedbacks',
  'images': 'Images',
  'notices': 'Notices',
  'followers': 'Followers',
  'averageRate': 'Rating',
  'startTime': 'Start',
  'description': 'Description',
  'status': 'Status',
  'responseText': 'Response',
  'duration': 'Duration',
  'endTime': 'End',
  'morephotosbtnlabel': 'See more photos',
  'reservebtnlabel':'Reserve',
  'followbtnlabel':'Follow',
  'callbtnlabel': 'Call now',
  'distance': 'Distance',
  'schedule_tabname': 'Schedule',
  'newrequests_tabname': 'New Requests',
  'backtopartnerdetails': 'Go my details',
  'cancelbtnlabel': 'Cancel',
  'savebtnlabel': 'Save',
  'welcomepagetext':'Welcome to SOSO :) For looking services please signin or join to our system.',
  'wrongpassword': 'Invalid password.',
  'wrongusername': 'Invalid phonenumber.',
  'wrongdetails': 'Invalid password or phonenumber.',
  'wrongname': 'Name should be contain more than 3 letters.',
  'uniquetelephonemessage': 'Phone number should be unique.',
  'my_location':'My location',
  'soso':'Soso',
  'emptyeventsmessage': " There aren't new events.",
  'acceptedeventmessage':' has accepted your request :)',
  'doneeventmessage':'You have done events please give your feedbacks.',
  'minimumrateerrormessage':'Minimum rate is 1.',
  'seeservices_btn_lbl':'See services',
  'today':'today',
  'month':'month',
  'week':'week',
  'day':'day',
  'radius_of_search':'Radius of search in km'
};
