// lang-es.ts

export const LANG_AM_NAME = 'am';

export const LANG_AM_TRANS = {
  'signout': 'Դուրս գալ',
  'myrequest_tabname' : 'Ամրագրումներ',
  'favorites_tabname' : 'Նախընտրածներ',
  'unacceptedrequests_tabname' : 'Չհաստատված',
  'acceptedrequests_tabname' : 'Հաստատված',
  'donerequests_tabname' : 'Կատարված',
  'name':'Անուն',
  'telephone': 'Հեռախոս',
  'password':'Գաղտնաբառ',
  'service': 'Ծառայություն',
  'signin':'Մուտք',
  'signup': 'Գրանցվել',
  'username': 'Username',
  'address': 'Հասցե',
  'feedbacks': 'Կարծիքներ',
  'images': 'Նկարներ',
  'notices': 'Նշումներ',
  'followers': 'Հետևորդներ',
  'averageRate': 'Գնահատական',
  'startTime': 'Սկիզբ',
  'description': 'Նկարագրություն',
  'status': 'Վիճակը',
  'responseText': 'Պատասխան',
  'duration': 'Տևողություն',
  'endTime': 'Ավարտ',
  'morephotosbtnlabel': 'Նայել նկարներ',
  'reservebtnlabel':'Ամրագրել',
  'followbtnlabel':'Հետևել',
  'callbtnlabel': 'Զանգել հիմա',
  'distance': 'Հեռավորությունը',
  'schedule_tabname': 'Իմ գրաֆիկը',
  'newrequests_tabname': 'Նոր ամրագրումներ',
  'backtopartnerdetails': 'Գնալ իմ էջ',
  'cancelbtnlabel': 'Չեղարկել',
  'savebtnlabel': 'Հիշել',
  'welcomepagetext':'Բարի գալուստ ՍՈՍՈ :) Ծառայություններ փնտրելու համար գրանցվիր կամ մուտք գործիր համակարգ:',
  'wrongpassword': 'Սխալ մուտքագրված գաղտնաբառ։',
  'wrongusername': 'Սխալ մուտքագրված հեռախոսահամար։',
  'wrongdetails': 'Սխալ մուտքագրված տվյալներ։',
  'wrongname': 'Անունի դաշտը չի կարող լինել 3-ից կարճ։',
  'uniquetelephonemessage': 'Նման հեռախոսահամար համակարգում արդեն գոյութոյւն ունի։',
  'my_location':'Իմ տեղը',
  'soso':'ՍՈՍՈ',
  'emptyeventsmessage': "Նոր ծանուցումներ չկան։",
  'acceptedeventmessage':'-ը ընդունել է Ձեր ամրագրումը :)',
  'doneeventmessage':'Դուք ունեք ավարտված ամրագրումներ խնդրում ենք թողնել Ձեր կարծիքը։',
  'minimumrateerrormessage':'Գնահատականը պարտադիր է։',
  'seeservices_btn_lbl':'Նայել գնացուցակը',
  'today':'այսօր',
  'month':'ամիս',
  'week':'շաբաթ',
  'day':'օր'
};
